// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Main.Models;

public partial class Book
{
    public int ID { get; set; }

    public string BookName { get; set; }

    public string Description { get; set; }

    public string ImageURL { get; set; }

    public string Text { get; set; }

    public int UserId { get; set; }

    public bool IsFrozen { get; set; }

    public virtual ICollection<BooksGenre> BooksGenres { get; set; } = new List<BooksGenre>();

    public virtual ICollection<Complaint> Complaints { get; set; } = new List<Complaint>();

    public virtual ICollection<ReadingList> ReadingLists { get; set; } = new List<ReadingList>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<UnfreezeApplication> UnfreezeApplications { get; set; } = new List<UnfreezeApplication>();

    public virtual User User { get; set; }
}