// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Main.Models;

public partial class BooksGenre
{
    public int ID { get; set; }

    public int? BookId { get; set; }

    public int? GenreId { get; set; }

    public virtual Book Book { get; set; }

    public virtual Genre Genre { get; set; }
}