// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Main.Models;

public partial class Complaint
{
    public int ID { get; set; }

    public int UserId { get; set; }

    public int? BookId { get; set; }

    public int? ReviewId { get; set; }

    public string Reason { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? TargetAuthorId { get; set; }

    public virtual Book Book { get; set; }

    public virtual Review Review { get; set; }

    public virtual User TargetAuthor { get; set; }

    public virtual User User { get; set; }
}