// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Main.Models;

public partial class Genre
{
    public int ID { get; set; }

    public string GenreName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<BooksGenre> BooksGenres { get; set; } = new List<BooksGenre>();
}