// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Main.Models;

public partial class JesterAndKingContext : DbContext
{
    public JesterAndKingContext()
    {
    }

    public JesterAndKingContext(DbContextOptions<JesterAndKingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Book> Books { get; set; }

    public virtual DbSet<BooksGenre> BooksGenres { get; set; }

    public virtual DbSet<Complaint> Complaints { get; set; }

    public virtual DbSet<Genre> Genres { get; set; }

    public virtual DbSet<ReadingList> ReadingLists { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RoleApplication> RoleApplications { get; set; }

    public virtual DbSet<UnfreezeApplication> UnfreezeApplications { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=Korzh;Initial Catalog=JesterAndKing;Integrated Security=True;Encrypt=True;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Books__3214EC27853369F7");

            entity.Property(e => e.BookName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.ImageURL).IsRequired();
            entity.Property(e => e.Text).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.Books)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Books__UserId__412EB0B6");
        });

        modelBuilder.Entity<BooksGenre>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__BooksGen__3214EC273C2A53F1");

            entity.HasOne(d => d.Book).WithMany(p => p.BooksGenres)
                .HasForeignKey(d => d.BookId)
                .HasConstraintName("FK__BooksGenr__BookI__46E78A0C");

            entity.HasOne(d => d.Genre).WithMany(p => p.BooksGenres)
                .HasForeignKey(d => d.GenreId)
                .HasConstraintName("FK__BooksGenr__Genre__47DBAE45");
        });

        modelBuilder.Entity<Complaint>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Complain__3214EC275FA7419F");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Reason).IsRequired();

            entity.HasOne(d => d.Book).WithMany(p => p.Complaints)
                .HasForeignKey(d => d.BookId)
                .HasConstraintName("FK__Complaint__BookI__571DF1D5");

            entity.HasOne(d => d.Review).WithMany(p => p.Complaints)
                .HasForeignKey(d => d.ReviewId)
                .HasConstraintName("FK__Complaint__Revie__5812160E");

            entity.HasOne(d => d.TargetAuthor).WithMany(p => p.ComplaintTargetAuthors)
                .HasForeignKey(d => d.TargetAuthorId)
                .HasConstraintName("FK__Complaint__Targe__14270015");

            entity.HasOne(d => d.User).WithMany(p => p.ComplaintUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Complaint__UserI__5629CD9C");
        });

        modelBuilder.Entity<Genre>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Genres__3214EC270AF271E9");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.GenreName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ReadingList>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReadingL__3214EC0720889623");

            entity.HasIndex(e => new { e.UserId, e.BookId }, "UQ__ReadingL__7456C06D947B88AE").IsUnique();

            entity.Property(e => e.AddedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Book).WithMany(p => p.ReadingLists)
                .HasForeignKey(d => d.BookId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ReadingLi__BookI__5165187F");

            entity.HasOne(d => d.User).WithMany(p => p.ReadingLists)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ReadingLi__UserI__5070F446");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Reviews__3214EC276DF2DAB8");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Text).IsRequired();

            entity.HasOne(d => d.Book).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.BookId)
                .HasConstraintName("FK__Reviews__BookId__4CA06362");

            entity.HasOne(d => d.User).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Reviews__UserId__4BAC3F29");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Roles__3214EC2720358BBC");

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<RoleApplication>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RoleAppl__3214EC07785BDFB4");

            entity.Property(e => e.ApplicationDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending");

            entity.HasOne(d => d.User).WithMany(p => p.RoleApplications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RoleAppli__UserI__5CD6CB2B");
        });

        modelBuilder.Entity<UnfreezeApplication>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Unfreeze__3214EC07CD2918E7");

            entity.Property(e => e.ApplicationDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Reason).IsRequired();
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TargetType)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.TargetBook).WithMany(p => p.UnfreezeApplications)
                .HasForeignKey(d => d.TargetBookId)
                .HasConstraintName("FK__UnfreezeA__Targe__6383C8BA");

            entity.HasOne(d => d.User).WithMany(p => p.UnfreezeApplications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UnfreezeA__UserI__619B8048");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Users__3214EC278E81096C");

            entity.HasIndex(e => e.Login, "UQ__Users__5E55825B1427E185").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Users__A9D1053491413750").IsUnique();

            entity.HasIndex(e => e.Nickname, "UQ__Users__CC6CD17E7AA14297").IsUnique();

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(70);
            entity.Property(e => e.Login)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Nickname)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Registration)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__Users__RoleId__3D5E1FD2");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}