// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Main.Models;

public partial class ReadingList
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int BookId { get; set; }

    public string Status { get; set; }

    public DateTime AddedDate { get; set; }

    public virtual Book Book { get; set; }

    public virtual User User { get; set; }
}