// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Main.Models;

public partial class Review
{
    public int ID { get; set; }

    public string Text { get; set; }

    public int Rating { get; set; }

    public int? UserId { get; set; }

    public int? BookId { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsFrozen { get; set; }

    public virtual Book Book { get; set; }

    public virtual ICollection<Complaint> Complaints { get; set; } = new List<Complaint>();

    public virtual User User { get; set; }
}