// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Main.Models;

public partial class RoleApplication
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public DateTime ApplicationDate { get; set; }

    public string Status { get; set; }

    public virtual User User { get; set; }
}