// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Main.Models;

public partial class User
{
    public int ID { get; set; }

    public DateTime Registration { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Nickname { get; set; }

    public int? RoleId { get; set; }

    public bool IsFrozen { get; set; }

    public virtual ICollection<Book> Books { get; set; } = new List<Book>();

    public virtual ICollection<Complaint> ComplaintTargetAuthors { get; set; } = new List<Complaint>();

    public virtual ICollection<Complaint> ComplaintUsers { get; set; } = new List<Complaint>();

    public virtual ICollection<ReadingList> ReadingLists { get; set; } = new List<ReadingList>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual Role Role { get; set; }

    public virtual ICollection<RoleApplication> RoleApplications { get; set; } = new List<RoleApplication>();

    public virtual ICollection<UnfreezeApplication> UnfreezeApplications { get; set; } = new List<UnfreezeApplication>();
}